// Generated by CoffeeScript 1.4.0
(function() {
  var ApplicationTag, Files, RedisObject, async,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require('async');

  RedisObject = require('./redis_object');

  Files = require('./files');

  /**
   * A helper for working with tags for an application/user combo.
  */


  ApplicationTag = (function(_super) {

    __extends(ApplicationTag, _super);

    function ApplicationTag(user, application, tag) {
      this.user = user;
      this.application = application;
      if (tag == null) {
        tag = null;
      }
      this.files = __bind(this.files, this);
      this.delete_all = __bind(this.delete_all, this);
      this["delete"] = __bind(this["delete"], this);
      this.save = __bind(this.save, this);
      this.all = __bind(this.all, this);
      this.find = __bind(this.find, this);
      this.list = __bind(this.list, this);
      this.taglist_prefix = __bind(this.taglist_prefix, this);
      ApplicationTag.__super__.constructor.call(this, tag);
      this.basename = "node-ios-ota::applications";
      this.object_name = 'tags';
    }

    /**
     * Returns the the prefix for the taglist.
     * @return {String} The taglist prefix for the current application
    */


    ApplicationTag.prototype.taglist_prefix = function() {
      return [this.basename, this.user, this.application, this.object_name].join('::');
    };

    /**
     * Returns the list of tags for the given user/application.
     * @param {Function} (fn) The callback function
    */


    ApplicationTag.prototype.list = function(fn) {
      return this.redis.smembers(this.taglist_prefix(), fn);
    };

    /**
     * Returns the information for the current application tag.
     * @param {String} (name) The name of the tag to retrieve
     * @param {Function} (fn) The callback function
     * TODO: Finish this
    */


    ApplicationTag.prototype.find = function(name, fn) {};

    /**
     * Returns the information for all the current application tags.
     * @param {Function} (fn) The callback function
     * TODO: Finish this
    */


    ApplicationTag.prototype.all = function(fn) {};

    /**
     * Inserts a new tag into the given application.
     * @param {String} (branch) The name of the branch to add
     * @param {Function} (fn) The callback function
    */


    ApplicationTag.prototype.save = function(fn) {
      var stat_add, status;
      stat_add = this.redis.sadd(this.taglist_prefix(), this.current);
      status = stat_add ? null : {
        message: "Error saving tag: `" + this.user + "/" + this.application + "/" + this.current + "`."
      };
      return fn(status, this.current);
    };

    /**
     * Deletes a single tag for the given application.
     * @param {String} (tag) The name of the target tag
     * @param {Function} The callback function
    */


    ApplicationTag.prototype["delete"] = function(tag, fn) {
      var _this = this;
      this.current = tag;
      this.redis.srem(this.taglist_prefix(), tag);
      return this.files().delete_all(function(err, reply) {
        return fn(null);
      });
    };

    /**
     * Deletes all of the tags for the current application.
     * @param {Function} The callback function
    */


    ApplicationTag.prototype.delete_all = function(fn) {
      var _this = this;
      return this.list(function(err, taglist) {
        return async.forEach(taglist, _this["delete"], fn);
      });
    };

    /**
     * Returns the list of files for the current tag.
     * @return {Object} The Files object for the current application
    */


    ApplicationTag.prototype.files = function() {
      return new Files(this.user, this.application, this.object_name, this.current);
    };

    return ApplicationTag;

  })(RedisObject);

  module.exports = ApplicationTag;

}).call(this);
