// Generated by CoffeeScript 1.4.0
(function() {
  var Filelist, RedisObject, async,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require('async');

  RedisObject = require('./redis_object');

  /**
   * A helper for working with filelists for a branch or tag of an application.
  */


  Filelist = (function(_super) {

    __extends(Filelist, _super);

    function Filelist(user, application, dtype) {
      this.user = user;
      this.application = application;
      this.dtype = dtype;
      Filelist.__super__.constructor.call(this, tag);
      this.basename = "node-ios-ota::applications";
      this.object_name = 'filelist';
    }

    return Filelist;

  })(RedisObject);

  module.exports = Filelist;

}).call(this);
