// Generated by CoffeeScript 1.4.0
(function() {
  var RedisSingleton, config, logger, redis;

  redis = require('redis');

  config = require('nconf');

  logger = require('../logger');

  /*
  Redis utility wrapper that acts as a singleton.
  */


  RedisSingleton = (function() {

    function RedisSingleton() {
      var _this = this;
      this.redis = new redis.createClient(config.get("redis_port"), config.get("redis_host"));
      this.redis.on("error", function(err) {
        logger.error(''.concat("Error connecting to redis://", config.get('redis_host'), ':', config.get('redis_port')));
        return logger.error("Retrying connection...");
      });
      return this.redis;
    }

    return RedisSingleton;

  })();

  module.exports = new RedisSingleton();

}).call(this);
