// Generated by CoffeeScript 1.3.3
(function() {
  var RedisObject, User, generate_identity,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  RedisObject = require('./redis_object');

  generate_identity = require('../identity').generate_identity;

  /**
   * Acts as a base class for all Redis-based objects.
  */


  User = (function(_super) {

    __extends(User, _super);

    function User() {
      this.update = __bind(this.update, this);

      this.save = __bind(this.save, this);

      this.find = __bind(this.find, this);

      this.all = __bind(this.all, this);
      User.__super__.constructor.apply(this, arguments);
      this.object_name = 'user';
    }

    /**
     * Returns all of the user objects with the given filter.
     * @param {Object} (filter) The object keys you wish to return (null is all)
     * @param {Function} (fn) The callback function
    */


    User.prototype.all = function(filter, fn) {
      var _this = this;
      if (filter == null) {
        filter = null;
      }
      this.current = null;
      if (!filter) {
        filter = {};
      }
      return this.redis.smembers(''.concat(this.prefix(), 's'), function(err, usernames) {
        if (filter.name && Object.keys(filter).length === 1) {
          return fn(err, usernames);
        }
      });
    };

    /**
     * Searches for the redis objects that match the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) The callback function
    */


    User.prototype.find = function(query, fn) {
      var _this = this;
      this.current = null;
      this.all({
        name: true
      }, function(err, usernames) {
        var _ref;
        if (_ref = query.name, __indexOf.call(usernames, _ref) >= 0) {
          return console.log("GOT IT");
        }
      });
      return fn(null, []);
    };

    /**
     * Searches for the redis object that matches the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) The callback function
    */


    /**
     * Adds a new redis object of the current type to the database.
     * @param {Object} (obj) The object to add
     * @param {Function} (fn) The callback function
    */


    User.prototype.save = function(fn) {
      var target, user_prefix,
        _this = this;
      if (!this.current) {
        return fn(null, false);
      }
      target = this.current;
      user_prefix = [this.prefix(), target.name].join('-');
      return this.all({
        name: true
      }, function(err, usernames) {
        var suc_add, suc_hm, success, _ref;
        if (_ref = target.name, __indexOf.call(usernames, _ref) >= 0) {
          _this.current = target;
          return fn(null, false);
        }
        target.secret = generate_identity();
        suc_add = _this.redis.sadd(''.concat(_this.prefix(), 's'), target.name);
        suc_hm = _this.redis.hmset(user_prefix, target);
        _this.current = target;
        success = suc_add && suc_hm;
        return fn(!success, _this.current);
      });
    };

    /**
     * Updates a redis object with the given parameters.
     * @param {Object} (obj) The object to merge with updates
     * @param {Function} (fn) The callback function
    */


    User.prototype.update = function(obj, fn) {
      var user_prefix;
      user_prefix = [this.prefix(), obj.name].join('-');
      if (!this.current) {
        return fn(null, false);
      }
      return fn(null, obj);
    };

    /**
     * Deletes a redis object that matches the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) the callback function
    */


    return User;

  })(RedisObject);

  module.exports = User;

}).call(this);
