// Generated by CoffeeScript 1.3.3
(function() {
  var RedisObject, UserApp, generate_identity,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RedisObject = require('./redis_object');

  generate_identity = require('../identity').generate_identity;

  /**
   * Acts as a base class for all Redis-based objects.
  */


  UserApp = (function(_super) {

    __extends(UserApp, _super);

    function UserApp(user, obj) {
      this.user = user;
      if (obj == null) {
        obj = null;
      }
      this.save = __bind(this.save, this);

      this.find = __bind(this.find, this);

      this.all = __bind(this.all, this);

      this.list = __bind(this.list, this);

      this.application_prefix = __bind(this.application_prefix, this);

      this.user_prefix = __bind(this.user_prefix, this);

      UserApp.__super__.constructor.call(this, obj);
      this.object_name = 'application';
    }

    /**
     * The applications prefix for the specified user.
    */


    UserApp.prototype.user_prefix = function() {
      return ''.concat(this.prefix(), 's', '::', this.user);
    };

    /**
     * The user-specific application prefix for a given application.
     * @param {String} (application) The name of the application
    */


    UserApp.prototype.application_prefix = function(application) {
      return [''.concat(this.user_prefix(), application)].join('::');
    };

    /**
     * Returns the list of application names for a given user.
     * @param {Function} (fn) The callback function
    */


    UserApp.prototype.list = function(fn) {
      return this.redis.smembers(this.user_prefix, fn);
    };

    /**
     * Returns all of the user objects with the given filter.
     * @param {Object} (filter) The object keys you wish to return (null is all)
     * @param {Function} (fn) The callback function
    */


    UserApp.prototype.all = function(filter, fn) {
      if (filter == null) {
        filter = null;
      }
    };

    /**
     * Searches for the redis objects that match the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) The callback function
    */


    UserApp.prototype.find = function(query, fn) {};

    /**
     * Searches for the redis object that matches the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) The callback function
    */


    /**
     * Adds a new redis object of the current type to the database.
     * @param {Object} (obj) The object to add
     * @param {Function} (fn) The callback function
    */


    UserApp.prototype.save = function(fn) {
      var target;
      if (!this.current) {
        return fn(null, false);
      }
      target = this.current;
      return console.log('target: ' + target);
    };

    /**
     * Deletes a redis object that matches the query.
     * @param {Object} (query) The query object to search
     * @param {Function} (fn) the callback function
    */


    return UserApp;

  })(RedisObject);

  module.exports = UserApp;

}).call(this);
