// Generated by CoffeeScript 1.4.0
(function() {
  var Application, CLI, WebServer, config, generate_identity, identity, logger, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  logger = require('./logger');

  CLI = require('./cli');

  config = require('nconf');

  _ref = require('./identity'), identity = _ref.identity, generate_identity = _ref.generate_identity;

  WebServer = require('./webserver');

  /*
  The base application class.
  */


  Application = (function() {

    function Application() {
      this.abort = __bind(this.abort, this);      this.cli = new CLI();
      this.ws = new WebServer();
    }

    /*
      Aborts the application with a message.
      @param {String} (msg) The message to abort the application with
    */


    Application.prototype.abort = function(msg) {
      logger.info(''.concat('Aborting Application: ', str, '...'));
      return process.exit(1);
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
