// Generated by CoffeeScript 1.3.3
(function() {
  var Application, CLI, Config, Identity, Logger, WebServer, generate_identity, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Logger = require('./logger');

  CLI = require('./cli');

  Config = require('./config');

  _ref = require('./identity'), Identity = _ref.Identity, generate_identity = _ref.generate_identity;

  WebServer = require('./webserver');

  /**
   * The base application class.
  */


  Application = (function() {

    function Application(pkg_info) {
      this.pkg_info = pkg_info;
      this.abort = __bind(this.abort, this);

      this.config = Config.get();
      this.logger = Logger.get();
      this.cli = new CLI(this.pkg_info, this.logger);
      this.identity = Identity.get();
      this.ws = new WebServer(this.config.get('port'), this.pkg_info);
    }

    Application.prototype.abort = function(str) {
      this.logger.info('aborting...');
      return process.exit(1);
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
