// Generated by CoffeeScript 1.4.0
(function() {
  var Application, CLI, Config, Identity, Logger, WebServer, generate_identity, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Logger = require('./logger');

  CLI = require('./cli');

  Config = require('./config');

  _ref = require('./identity'), Identity = _ref.Identity, generate_identity = _ref.generate_identity;

  WebServer = require('./webserver');

  /**
   * The base application class.
  */


  Application = (function() {

    function Application() {
      this.abort = __bind(this.abort, this);      this.config = Config.get();
      this.logger = Logger.get();
      this.cli = new CLI();
      this.identity = Identity.get();
      this.ws = new WebServer(this.config.get('port'));
    }

    /**
     * Aborts the application with a message.
     * @param {String} (msg) The message to abort the application with
    */


    Application.prototype.abort = function(msg) {
      this.logger.info(''.concat('Aborting Application: ', str, '...'));
      return process.exit(1);
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
