// Generated by CoffeeScript 1.3.3
(function() {
  var Logger, crypto, log4js,
    _this = this;

  crypto = require('crypto');

  log4js = require('log4js');

  Logger = (function() {

    function Logger() {
      var logger;
      logger = log4js.getLogger();
    }

    return Logger;

  })();

  module.exports = {
    generate_identity: function() {
      return crypto.randomBytes(8).toString('hex');
    },
    logger: function() {
      if (typeof instance !== "undefined" && instance !== null) {
        return instances;
      }
      return new Logger;
    }
  };

}).call(this);
