// Generated by CoffeeScript 1.4.0
(function() {
  var Config, Singleton, nconf,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  nconf = require('nconf');

  Singleton = require('./singleton');

  /**
   * Config class that acts as a singleton.
  */


  Config = (function(_super) {

    __extends(Config, _super);

    function Config() {
      return nconf;
    }

    return Config;

  })(Singleton);

  module.exports = Config;

}).call(this);
