// Generated by CoffeeScript 1.4.0
(function() {
  var crypto, filemd5, fs;

  fs = require('fs');

  crypto = require('crypto');

  /*
  Generates an md5sum for a given file.
  @param {Integer} (filepath) The path to the file you want an md5sum of
  @return {String} The md5sum of the file
  */


  filemd5 = function(filepath, cb) {
    return fs.readFile(filepath, 'binary', function(err, data) {
      if (err) {
        console.log(err);
        return cb(err, "lame");
      } else {
        return cb(err, crypto.createHash('md5').update(data).digest('hex'));
      }
    });
  };

  module.exports = filemd5;

}).call(this);
