// Generated by CoffeeScript 1.4.0
(function() {
  var crypto, generate_identity;

  crypto = require('crypto');

  /*
  Generates a new identity.
  @param {Integer} (length) The length of the identity bytestring
  @return {String} The randombyte hex string
  */


  generate_identity = function(length) {
    if (length == null) {
      length = 8;
    }
    return crypto.randomBytes(length).toString('hex');
  };

  module.exports = {
    generate_identity: generate_identity,
    identity: generate_identity()
  };

}).call(this);
