// Generated by CoffeeScript 1.4.0
(function() {
  var MixlibLog, logger, winston;

  winston = require('winston');

  MixlibLog = require('winston-mixlib-log').MixlibLog;

  logger = new winston.Logger({
    transports: [
      new MixlibLog({
        timestamp: true
      })
    ]
  });

  logger.log = function() {
    return winston.Logger.prototype.log.apply(this, arguments);
  };

  module.exports = logger;

}).call(this);
