// Generated by CoffeeScript 1.3.3
(function() {
  var formidable, fs, setup_routing;

  fs = require('fs');

  formidable = require('formidable');

  /**
   * Sets up the routing
  */


  setup_routing = function(app, logger, pkg_info) {
    var _this = this;
    this.app = app;
    this.logger = logger;
    this.pkg_info = pkg_info;
    this.app.get('/', function(req, res) {
      return res.json(200, {
        name: _this.pkg_info.name,
        version: _this.pkg_info.version
      });
    });
    this.app.get('/:user/:app/branches', function(req, res) {
      return res.json(200, {
        name: [req.params.user, req.params.app, 'branches'].join('/'),
        branches: fs.readdirSync([_this.config.get('repository'), req.params.user, req.params.app].join('/'))
      });
    });
    return this.app.post('/releases', function(req, res) {
      var form;
      this.logger.info(req);
      form = formidable.IncomingForm();
      return form.parse(req, function(err, fields, files) {
        return res.json(200, {
          message: "Recieved Upload",
          fields: fields,
          files: files
        });
      });
    });
  };

  module.exports = {
    setup_routing: setup_routing
  };

}).call(this);
