// Generated by CoffeeScript 1.4.0

/**
 * Class that acts as a singleton.
*/


(function() {
  var Singleton;

  Singleton = (function() {

    function Singleton() {}

    Singleton._instance = null;

    Singleton.get = function(args) {
      return this._instance || (this._instance = (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(this, args, function(){}));
    };

    return Singleton;

  })();

  module.exports = Singleton;

}).call(this);
