// Generated by CoffeeScript 1.3.3
(function() {
  var app, common, formidable, restify;

  common = require('./common');

  restify = require('restify');

  formidable = require('formidable');

  app = restify.createServer();

  module.exports = {
    start_server: function() {
      this.setup_routes();
      app.listen('3000');
      return console.log("Webserver is up at: http://0.0.0.0:%s", 3000);
    },
    setup_routes: function() {
      app.get('/', function(req, res) {
        return res.json(200, {
          name: app_info.name,
          version: app_info.version
        });
      });
      app.post('/test', function(req, res) {
        var form;
        console.log(req);
        form = formidable.IncomingForm();
        return form.parse(req, function(err, fields, files) {
          return res.json(200, {
            message: "Recieved Upload",
            fields: fields,
            files: files
          });
        });
      });
    }
  };

}).call(this);
